#ifndef __FULLSCORE_CONSTANTS_HEADER
#define __FULLSCORE_CONSTANTS_HEADER




#define DURATION_WHOLE 1
#define DURATION_HALF 2
#define DURATION_QUARTER 4
#define DURATION_EIGHTH 8
#define DURATION_SIXTEENTH 16
#define DURATION_THIRTYSECOND 32
#define DURATION_SIXTYFOURTH 64




#endif
