#pragma once



namespace Transform
{
   std::string const ADD_DOT_TRANSFORM_IDENTIFIER = "ADD_DOT";
   std::string const APPEND_NOTE_TRANSFORM_IDENTIFIER = "APPEND_NOTE";
   std::string const ASCEND_TRANSFORM_IDENTIFIER = "ASCEND";
   std::string const CLEAR_MEASURE_TRANSFORM_IDENTIFIER = "CLEAR_MEASURE";
   std::string const DESCEND_TRANSFORM_IDENTIFIER = "DESCEND";
   std::string const DOUBLE_DURATION_TRANSFORM_IDENTIFIER = "DOUBLE_DURATION";
   std::string const ERASE_NOTE_TRANSFORM_IDENTIFIER = "ERASE_NOTE";
   std::string const HALF_DURATION_TRANSFORM_IDENTIFIER = "HALF_DURATION";
   std::string const INSERT_NOTE_TRANSFORM_IDENTIFIER = "INSERT_NOTE";
   std::string const INVERT_TRANSFORM_IDENTIFIER = "INVERT";
   std::string const NOTES_AT_TRANSFORM_IDENTIFIER = "NOTES_AT";
   std::string const OCTATONIC_1_TRANSFORM_IDENTIFIER = "OCTATONIC_1";
   std::string const REMOVE_DOT_TRANSFORM_IDENTIFIER = "REMOVE_DOT";
   std::string const RETROGRADE_TRANSFORM_IDENTIFIER = "RETROGRADE";
   std::string const SPLIT_NOTE_TRANSFORM_IDENTIFIER = "SPLIT_NOTE";
   std::string const STACK_TRANSFORM_IDENTIFIER = "STACK";
   std::string const TOGGLE_REST_TRANSFORM_IDENTIFIER = "TOGGLE_REST";
   std::string const TRANSPOSE_TRANSFORM_IDENTIFIER = "TRANSPOSE";

   static const std::vector<std::string> ALL_IDENTIFIERS = {
      ADD_DOT_TRANSFORM_IDENTIFIER,
      APPEND_NOTE_TRANSFORM_IDENTIFIER,
      ASCEND_TRANSFORM_IDENTIFIER,
      CLEAR_MEASURE_TRANSFORM_IDENTIFIER,
      DESCEND_TRANSFORM_IDENTIFIER,
      DOUBLE_DURATION_TRANSFORM_IDENTIFIER,
      ERASE_NOTE_TRANSFORM_IDENTIFIER,
      HALF_DURATION_TRANSFORM_IDENTIFIER,
      INSERT_NOTE_TRANSFORM_IDENTIFIER,
      INVERT_TRANSFORM_IDENTIFIER,
      NOTES_AT_TRANSFORM_IDENTIFIER,
      OCTATONIC_1_TRANSFORM_IDENTIFIER,
      REMOVE_DOT_TRANSFORM_IDENTIFIER,
      RETROGRADE_TRANSFORM_IDENTIFIER,
      SPLIT_NOTE_TRANSFORM_IDENTIFIER,
      STACK_TRANSFORM_IDENTIFIER,
      TOGGLE_REST_TRANSFORM_IDENTIFIER,
      TRANSPOSE_TRANSFORM_IDENTIFIER,
   };
};



